title:
    fr: 'Projet Okatea'
    en: 'Okatea project'
desc:
    fr: 'Un autre CMS modulaire en PHP'
    en: 'Another modular CMS in PHP'
home_page:
    item:
        fr: ''
        en: ''
    details:
        fr: ''
        en: ''
title_tag:
    fr: ''
    en: ''
meta_description:
    fr: ''
    en: ''
meta_keywords:
    fr: ''
    en: ''
schedule:
    fr: ''
    en: ''
address:
    street: ''
    street_2: ''
    code: ''
    city: ''
    country: ''
    tel: ''
    mobile: ''
    fax: ''
gps:
    lat: ''
    long: ''
company:
    name: ''
    com_name: ''
    siret: ''
leader:
    name: ''
    firstname: ''
email:
    to: contact@okatea.org
    from: contact@okatea.org
    name: Okatea
    transport: mail
    smtp:
        host: ''
        port: 25
        username: ''
        password: ''
    sendmail: ''
language: fr
timezone: Europe/Paris
admin_lang_switcher: true
app_path: /okatea/
domain: localhost
htmlpurifier_disabled: false
slug_type: ascii
updates:
    enabled: true
    url: 'http://repository.okatea.org/packages/versions.xml'
    type: stable
repositories:
    themes:
        enabled: true
        list:
            'Okatea themes': 'http://repository.okatea.org/themes/%VERSION%/index.xml'
    modules:
        enabled: true
        list:
            'Okatea modules': 'http://repository.okatea.org/modules/%VERSION%/index.xml'
themes:
    desktop: Okatea
    mobile: ''
    tablet: ''
jquery_ui:
    public: black-tie
    admin: redmond
enable_admin_bar: true
admin_menu_position: left
maintenance:
    public: false
    admin: false
user_visit:
    timeout: 1800
    remember_time: 1209600
log_admin:
    ttl_months: 3
news_feed:
    enabled: false
    url:
        fr: 'http://okatea.org/fr/actualites/rss'
        en: 'http://okatea.org/en/news/rss'
navigation_tpl:
    default: default
    usables: {  }
users:
    custom_fields_enabled: false
    gravatar:
        enabled: true
        default_image: mm
        rating: g
    pages:
        login: true
        register: true
        log_reg: false
        forget_password: true
        profile: true
    registration:
        merge_username_email: false
        mail_new_registration: false
        mail_new_registration_recipients: {  }
        validation_email: true
        validation_admin: false
        auto_log_after_registration: false
        user_choose_group: false
        default_group: 4
    templates:
        forgotten_password:
            default: default
            usables: {  }
        login:
            default: default
            usables: {  }
        login_register:
            default: default
            usables: {  }
        profile:
            default: default
            usables: {  }
        register:
            default: default
            usables: {  }
        user_bar:
            default: default
            usables: {  }
users_filters:
    public_default_nb_per_page: 10
    admin_default_nb_per_page: 10
