# default Okatea routes
# do not remove this file

404:
    path:     /fr/404
    defaults: { _controller: Tao\Core\Controller::serve404 }

503:
    path:     /fr/503
    defaults: { _controller: Tao\Core\Controller::serve503 }
    
remove_trailing_slash:
    path:     /fr/{url}
    defaults: { _controller: Tao\Core\Controller::removeTrailingSlash }
    requirements:
        url: .*/$
        _method: GET
