# default Okatea routes
# do not remove this file


home:
    path:     /
    defaults: { controller: 'Okatea\Admin\Controller\Home::homePage' }


#
# Error pages
#

401:
    path:     /401
    defaults: { controller: 'Okatea\Admin\Controller::serve401' }
    
404:
    path:     /404
    defaults: { controller: 'Okatea\Admin\Controller::serve404' }

503:
    path:     /503
    defaults: { controller: 'Okatea\Admin\Controller::serve503' }


#
# Admin login/logout/forget-password pages
#

login:
    path:     /login
    defaults: { controller: 'Okatea\Admin\Controller\Connexion::login' }

logout:
    path:     /logout
    defaults: { controller: 'Okatea\Admin\Controller\Connexion::logout' }

forget_password:
    path:     /forget-password
    defaults: { controller: 'Okatea\Admin\Controller\Connexion::forget_password' }


#
# Users management pages
#

Users_index:
    path:     /users/{page}
    defaults: { controller: 'Okatea\Admin\Controller\Users\Index::page', page: 1 }
    requirements:
        page:  \d+

User_profile:
    path:     /profile
    defaults: { controller: 'Okatea\Admin\Controller\Users\User::profile' }

Users_add:
    path:     /users/add
    defaults: { controller: 'Okatea\Admin\Controller\Users\User::add' }

Users_edit:
    path:     /user/{user_id}
    defaults: { controller: 'Okatea\Admin\Controller\Users\User::edit' }
    requirements:
        user_id:  \d+

Users_groups:
    path:     /users/groups
    defaults: { controller: 'Okatea\Admin\Controller\Users\Groups::index' }

Users_groups_add:
    path:     /users/groups/add
    defaults: { controller: 'Okatea\Admin\Controller\Users\Groups::add' }

Users_groups_edit:
    path:     /users/group/{group_id}
    defaults: { controller: 'Okatea\Admin\Controller\Users\Groups::edit' }
    requirements:
        group_id:  \d+
        
Users_display:
    path:     /users/display
    defaults: { controller: 'Okatea\Admin\Controller\Users\Display::page' }

Users_config:
    path:     /users/configuration
    defaults: { controller: 'Okatea\Admin\Controller\Users\Config::page' }


#
# Configuration pages
#

config_general:
    path:     /configuration/general
    defaults: { controller: 'Okatea\Admin\Controller\Config\General::page' }

config_display:
    path:     /configuration/display
    defaults: { controller: 'Okatea\Admin\Controller\Config\Display::page' }

config_l10n:
    path:     /configuration/localization
    defaults: { controller: 'Okatea\Admin\Controller\Config\L10n::index' }

config_l10n_add_language:
    path:     /configuration/localization/language/add
    defaults: { controller: 'Okatea\Admin\Controller\Config\L10n::add' }

config_l10n_edit_language:
    path:     /configuration/localization/language/{language_id}
    defaults: { controller: 'Okatea\Admin\Controller\Config\L10n::edit' }
    requirements:
        language_id:  \d+

config_modules:
    path:     /configuration/modules
    defaults: { controller: 'Okatea\Admin\Controller\Config\Modules::page' }

config_themes:
    path:     /configuration/themes
    defaults: { controller: 'Okatea\Admin\Controller\Config\Themes::page' }

config_theme:
    path:     /configuration/theme/{theme_id}
    defaults: { controller: 'Okatea\Admin\Controller\Config\Theme::page' }

config_navigation:
    path:     /configuration/navigation
    defaults: { controller: 'Okatea\Admin\Controller\Config\Navigation::page' }

config_permissions:
    path:     /configuration/permissions
    defaults: { controller: 'Okatea\Admin\Controller\Config\Permissions::page' }

config_tools:
    path:     /configuration/tools
    defaults: { controller: 'Okatea\Admin\Controller\Config\Tools::page' }

config_infos:
    path:     /configuration/infos
    defaults: { controller: 'Okatea\Admin\Controller\Config\Infos::page' }

config_update:
    path:     /configuration/update
    defaults: { controller: 'Okatea\Admin\Controller\Config\Update::page' }

config_logadmin:
    path:     /configuration/logadmin/{page}
    defaults: { controller: 'Okatea\Admin\Controller\Config\Logadmin::page', page: 1 }
    requirements:
        page:  \d+

config_router:
    path:     /configuration/router
    defaults: { controller: 'Okatea\Admin\Controller\Config\Router::page' }

config_advanced:
    path:     /configuration/advanced
    defaults: { controller: 'Okatea\Admin\Controller\Config\Advanced::page' }

