# default Okatea routes
# do not remove this file

home:
    path:     /
    defaults: { _controller: Tao\Admin\Controller\Home::homePage }
    
404:
    path:     /404
    defaults: { _controller: Tao\Admin\Controller::serve404 }

503:
    path:     /503
    defaults: { _controller: Tao\Admin\Controller::serve503 }

login:
    path:     /login
    defaults: { _controller: Tao\Admin\Controller\Connexion::login }

logout:
    path:     /logout
    defaults: { _controller: Tao\Admin\Controller\Connexion::logout }

forget_password:
    path:     /forget-password
    defaults: { _controller: Tao\Admin\Controller\Connexion::forget_password }


config_general:
    path:     /configuration/general
    defaults: { _controller: Tao\Admin\Controller\Config\General::page }

config_display:
    path:     /configuration/display
    defaults: { _controller: Tao\Admin\Controller\Config\Display::page }

config_languages:
    path:     /configuration/languages
    defaults: { _controller: Tao\Admin\Controller\Config\Languages::page }

config_modules:
    path:     /configuration/modules
    defaults: { _controller: Tao\Admin\Controller\Config\Modules::page }

config_navigation:
    path:     /configuration/navigation
    defaults: { _controller: Tao\Admin\Controller\Config\Navigation::page }

config_permissions:
    path:     /configuration/permissions
    defaults: { _controller: Tao\Admin\Controller\Config\Permissions::page }

config_tools:
    path:     /configuration/tools
    defaults: { _controller: Tao\Admin\Controller\Config\Tools::page }

config_infos:
    path:     /configuration/infos
    defaults: { _controller: Tao\Admin\Controller\Config\Infos::page }

config_update:
    path:     /configuration/update
    defaults: { _controller: Tao\Admin\Controller\Config\Update::page }

config_logadmin:
    path:     /configuration/logadmin
    defaults: { _controller: Tao\Admin\Controller\Config\Logadmin::page }

config_router:
    path:     /configuration/router
    defaults: { _controller: Tao\Admin\Controller\Config\Router::page }

config_advanced:
    path:     /configuration/advanced
    defaults: { _controller: Tao\Admin\Controller\Config\Advanced::page }

