# default Okatea routes
# do not remove this file

404:
    path:     /404
    defaults: { _controller: Tao\Website\Controller::serve404 }

503:
    path:     /503
    defaults: { _controller: Tao\Website\Controller::serve503 }

remove_trailing_slash:
    path:     /{url}
    defaults: { _controller: Tao\Core\Controller::removeTrailingSlash }
    requirements:
        url: .*/$
        _method: GET
