<?php

$GLOBALS['__l10n']['c_a_config_display'] = 'Display configuration';

$GLOBALS['__l10n']['c_a_config_display_public_part'] = 'Public part';
$GLOBALS['__l10n']['c_a_config_display_admin_part'] = 'Admin part';

$GLOBALS['__l10n']['c_a_config_display_admin_bar'] = 'Display the admin bar for administrators';
$GLOBALS['__l10n']['c_a_config_display_admin_bar_note'] = 'The admin bar is always visible for super administrators';

$GLOBALS['__l10n']['c_a_config_display_choose_theme'] = 'Choose a theme';
$GLOBALS['__l10n']['c_a_config_display_choose_jquery_ui_theme'] = 'Choose a jQuery UI theme';

$GLOBALS['__l10n']['c_a_config_display_menu_pos'] = 'Menu position';
$GLOBALS['__l10n']['c_a_config_display_theme'] = 'Theme';
$GLOBALS['__l10n']['c_a_config_display_current_theme'] = ' (current)';
$GLOBALS['__l10n']['c_a_config_display_choose_theme_note'] = 'If you change the theme, remember to empty the cache of your browser.';
$GLOBALS['__l10n']['c_a_config_display_upload_theme'] = 'Or upload a theme';
$GLOBALS['__l10n']['c_a_config_display_upload_theme_note'] = 'This must be a zip file generated by the <a href="http://jqueryui.com/themeroller/">ThemeRoller</a>.';
$GLOBALS['__l10n']['c_a_config_display_compress_output'] = 'Enable compression of pages';

$GLOBALS['__l10n']['c_a_config_display_not_zip_file'] = 'Not a zip file.';
$GLOBALS['__l10n']['c_a_config_display_unable_move_file'] = 'Can not move the file on the server.';
$GLOBALS['__l10n']['c_a_config_display_empty_zip_file'] = 'Empty zip file.';
$GLOBALS['__l10n']['c_a_config_display_not_valid_theme'] = 'The zip file does not appear to be a valid theme.';