# default Okatea routes
# do not remove this file

homePage:
    path:     /
    defaults: { controller: Okatea\Website\Controller::homePage }
    
401:
    path:     /401
    defaults: { controller: Okatea\Website\Controller::serve401 }

404:
    path:     /404
    defaults: { controller: Okatea\Website\Controller::serve404 }

503:
    path:     /503
    defaults: { controller: Okatea\Website\Controller::serve503 }

usersLogin:
    path:     /connexion
    defaults: { controller: 'UsersController::usersLogin' }

usersLogout:
    path:     /deconnexion
    defaults: { controller: 'UsersController::usersLogout' }

usersProfile:
    path:     /profil
    defaults: { controller: 'UsersController::usersProfile' }

usersRegister:
    path:     /inscription
    defaults: { controller: 'UsersController::usersRegister' }

usersLoginRegister:
    path:     /connexion-inscription
    defaults: { controller: 'UsersController::usersLoginRegister' }

usersForgetPassword:
    path:     /mot-de-passe-oublie
    defaults: { controller: 'UsersController::usersForgetPassword' }

remove_trailing_slash:
    path:     /{url}
    defaults: { controller: Okatea\Tao\Controller::removeTrailingSlash }
    requirements:
        url: .*/$
        _method: GET
