
newsList:
    path:     /actualites
    defaults: { _controller: 'newsController::newsList' }
    
newsCategory:
    path:     /actualites/{slug}
    defaults: { _controller: 'newsController::newsCategory' }
    requirements: { slug: '.+' }
    
newsItem:
    path:     /actualite/{slug}
    defaults: { _controller: 'newsController::newsItem' }
    
newsFeed:
    path:     /actualites/rss
    defaults: { _controller: 'newsController::newsFeed' }
    